"""
Internationalisation (i18n) for Genesis Swarm — English and French.

Luxembourg fund industry operates in EN, FR, DE, and LB.
This module covers EN + FR (the two most critical for CSSF-regulated entities).

Usage:
    from genesis_swarm.shared.i18n import t, get_language

    # In a FastAPI endpoint:
    @app.get("/api/v1/status")
    def status(lang: str = Depends(detect_language)):
        return {"message": t("swarm.running", lang)}

    # In a report template:
    t("alert.severity.CRITICAL", "fr")   # → "CRITIQUE"
"""

from __future__ import annotations

import os
from typing import Optional

# ── Translation catalogue ─────────────────────────────────────────────────────
# Key format: "namespace.key" — all lowercase
# Add new keys here; missing keys fall back to English

_CATALOGUE: dict[str, dict[str, str]] = {
    # ── Swarm status ───────────────────────────────────────────────────────
    "swarm.running": {
        "en": "Swarm is running",
        "fr": "L'essaim est opérationnel",
    },
    "swarm.starting": {
        "en": "Swarm is starting",
        "fr": "L'essaim démarre",
    },
    "swarm.stopped": {
        "en": "Swarm has stopped",
        "fr": "L'essaim s'est arrêté",
    },
    "swarm.healthy_bots": {
        "en": "{n} bots healthy",
        "fr": "{n} agents opérationnels",
    },
    # ── Alert severities ───────────────────────────────────────────────────
    "alert.severity.INFO": {
        "en": "Information",
        "fr": "Information",
    },
    "alert.severity.WARNING": {
        "en": "Warning",
        "fr": "Avertissement",
    },
    "alert.severity.CRITICAL": {
        "en": "Critical",
        "fr": "Critique",
    },
    "alert.severity.EMERGENCY": {
        "en": "Emergency",
        "fr": "Urgence",
    },
    # ── Consensus ─────────────────────────────────────────────────────────
    "consensus.reached": {
        "en": "Consensus reached",
        "fr": "Consensus atteint",
    },
    "consensus.failed": {
        "en": "Consensus failed",
        "fr": "Échec du consensus",
    },
    "consensus.view_change": {
        "en": "View change triggered",
        "fr": "Changement de vue déclenché",
    },
    # ── Bot types ─────────────────────────────────────────────────────────
    "bot.NAV_DETECTOR": {
        "en": "NAV Detector",
        "fr": "Détecteur VNI",
    },
    "bot.CARGO_BOT": {
        "en": "Cargo Bot",
        "fr": "Agent cargo",
    },
    "bot.COMMODITY_MONITOR": {
        "en": "Fuel Bot",
        "fr": "Agent carburant",
    },
    "bot.SANCTIONS_BOT": {
        "en": "Sanctions Bot",
        "fr": "Agent sanctions",
    },
    "bot.FX_BOT": {
        "en": "FX Bot",
        "fr": "Agent change",
    },
    "bot.COMPLIANCE_BOT": {
        "en": "Compliance Bot",
        "fr": "Agent conformité",
    },
    "bot.SUCCESSION_BOT": {
        "en": "Succession Bot",
        "fr": "Agent succession",
    },
    "bot.SOVEREIGN_BOT": {
        "en": "Sovereign Bot",
        "fr": "Agent souverain",
    },
    "bot.ASSET_TRACKER": {
        "en": "Yacht Guardian",
        "fr": "Gardien yacht",
    },
    "bot.SATELLITE_ANALYTICS": {
        "en": "Orbital Bot",
        "fr": "Agent orbital",
    },
    "bot.ADVERSARIAL_TESTER": {
        "en": "Shadow Bot",
        "fr": "Agent fantôme",
    },
    # ── Auth ──────────────────────────────────────────────────────────────
    "auth.login_success": {
        "en": "Login successful",
        "fr": "Connexion réussie",
    },
    "auth.invalid_credentials": {
        "en": "Invalid credentials",
        "fr": "Identifiants invalides",
    },
    "auth.account_locked": {
        "en": "Account locked. Try again in {n} seconds.",
        "fr": "Compte verrouillé. Réessayez dans {n} secondes.",
    },
    "auth.token_expired": {
        "en": "Session expired. Please log in again.",
        "fr": "Session expirée. Veuillez vous reconnecter.",
    },
    # ── PDF report ────────────────────────────────────────────────────────
    "report.title": {
        "en": "AI Monitoring Compliance Report",
        "fr": "Rapport de conformité de surveillance IA",
    },
    "report.generated_by": {
        "en": "Generated by Genesis Swarm",
        "fr": "Généré par Genesis Swarm",
    },
    "report.merkle_integrity": {
        "en": "Audit Chain Integrity",
        "fr": "Intégrité de la chaîne d'audit",
    },
    "report.alert_timeline": {
        "en": "Alert Timeline",
        "fr": "Chronologie des alertes",
    },
    "report.bot_snapshot": {
        "en": "Bot Status Snapshot",
        "fr": "Instantané du statut des agents",
    },
    # ── Errors ────────────────────────────────────────────────────────────
    "error.not_found": {
        "en": "Not found",
        "fr": "Introuvable",
    },
    "error.forbidden": {
        "en": "Forbidden",
        "fr": "Accès refusé",
    },
    "error.server_error": {
        "en": "Internal server error",
        "fr": "Erreur interne du serveur",
    },
}

_SUPPORTED_LANGUAGES = {"en", "fr"}
_DEFAULT_LANGUAGE = os.getenv("GENESIS_DEFAULT_LANG", "en").lower()


def t(key: str, lang: Optional[str] = None, **kwargs) -> str:
    """
    Translate key to lang. Falls back to English if key or lang not found.

    Examples:
        t("alert.severity.CRITICAL")           → "Critical"
        t("alert.severity.CRITICAL", "fr")     → "Critique"
        t("swarm.healthy_bots", "fr", n=7)     → "7 agents opérationnels"
        t("nonexistent.key", "fr")             → "nonexistent.key"  (key fallback)
    """
    lang = (lang or _DEFAULT_LANGUAGE).lower()[:2]
    if lang not in _SUPPORTED_LANGUAGES:
        lang = "en"

    entry = _CATALOGUE.get(key)
    if not entry:
        return key  # Return key itself as last-resort fallback

    text = entry.get(lang) or entry.get("en") or key
    if kwargs:
        try:
            text = text.format(**kwargs)
        except KeyError:
            pass
    return text


def detect_language(accept_language: Optional[str] = None) -> str:
    """
    Parse Accept-Language header and return the best supported language.

    Examples:
        "fr-FR,fr;q=0.9,en;q=0.8"  → "fr"
        "de-DE,de;q=0.9"            → "en"  (de not supported → fallback)
        None                         → default language from env
    """
    if not accept_language:
        return _DEFAULT_LANGUAGE

    # Parse quality-weighted list: "fr-FR,fr;q=0.9,en;q=0.8"
    candidates = []
    for part in accept_language.split(","):
        part = part.strip()
        if ";q=" in part:
            lang_tag, q_str = part.rsplit(";q=", 1)
            try:
                q = float(q_str)
            except ValueError:
                q = 1.0
        else:
            lang_tag = part
            q = 1.0
        lang_code = lang_tag.strip().lower()[:2]
        candidates.append((q, lang_code))

    candidates.sort(key=lambda x: -x[0])
    for _, lang_code in candidates:
        if lang_code in _SUPPORTED_LANGUAGES:
            return lang_code

    return _DEFAULT_LANGUAGE


def supported_languages() -> list[str]:
    return sorted(_SUPPORTED_LANGUAGES)


def catalogue_keys() -> list[str]:
    return sorted(_CATALOGUE.keys())
