'use client'

import { useState, useCallback, useRef } from 'react'
import { ArrowLeft, FileText, Download, Copy, CheckCheck, Loader2, AlertTriangle, Globe, Info } from 'lucide-react'

const API = process.env.NEXT_PUBLIC_API_URL || 'https://damansh-genesis-swarm.hf.space'

interface SFDRResult {
  fund_name: string
  sfdr_article: number
  language: string
  disclosure: string
  sections: string[]
  regulation_refs: string[]
  cost_eur: number
  generated_at: string
  disclaimer: string
}

function Select({ value, onChange, options, label }: { value: string; onChange: (v: string) => void; options: {value: string; label: string}[]; label: string }) {
  return (
    <div>
      <label className="block text-[10px] text-[rgba(255,255,255,0.4)] uppercase tracking-wider mb-1">{label}</label>
      <select value={value} onChange={e => onChange(e.target.value)}
        className="w-full bg-[rgba(255,255,255,0.04)] border border-[rgba(255,255,255,0.12)] rounded px-3 py-2 text-sm text-white focus:outline-none focus:border-[rgba(0,170,255,0.5)]">
        {options.map(o => <option key={o.value} value={o.value} className="bg-[#0a0f14]">{o.label}</option>)}
      </select>
    </div>
  )
}

function Field({ value, onChange, label, placeholder, multiline = false }: { value: string; onChange: (v: string) => void; label: string; placeholder?: string; multiline?: boolean }) {
  const cls = "w-full bg-[rgba(255,255,255,0.04)] border border-[rgba(255,255,255,0.12)] rounded px-3 py-2 text-sm text-white placeholder-[rgba(255,255,255,0.25)] focus:outline-none focus:border-[rgba(0,170,255,0.5)]"
  return (
    <div>
      <label className="block text-[10px] text-[rgba(255,255,255,0.4)] uppercase tracking-wider mb-1">{label}</label>
      {multiline
        ? <textarea value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} rows={3} className={cls + ' resize-none'} />
        : <input type="text" value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} className={cls} />}
    </div>
  )
}

const ARTICLE_INFO = {
  '6': { label: 'Article 6', color: '#aaaaaa', desc: 'Does not promote environmental/social characteristics and has no sustainable investment objective. Must explain why PAI is not considered (or if it is).' },
  '8': { label: 'Article 8 — Light Green', color: '#00aaff', desc: 'Promotes environmental or social characteristics, or a combination. May include some sustainable investments. Must disclose how characteristics are met.' },
  '9': { label: 'Article 9 — Dark Green', color: '#00ff88', desc: 'Has sustainable investment as its objective. 100% sustainable investments (with allowance for hedging/cash). Most stringent disclosure requirements.' },
}

export default function SFDRPage() {
  const [form, setForm] = useState({
    fund_name: '', fund_type: 'AIF', sfdr_article: '8', manager_name: '',
    investment_strategy: '', sustainability_objective: '', esg_features: '',
    pai_considered: true, pai_indicators: '', benchmark_index: '', language: 'en',
  })
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState<SFDRResult | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)

  const set = (k: string, v: string | boolean) => setForm(p => ({ ...p, [k]: v }))

  const generate = useCallback(async () => {
    if (!form.fund_name.trim()) { setError('Fund name is required'); return }
    setLoading(true); setError(null); setResult(null)
    try {
      const res = await fetch(`${API}/api/v1/sfdr/generate`, {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ...form, sfdr_article: parseInt(form.sfdr_article), pai_considered: form.pai_considered }),
      })
      if (!res.ok) throw new Error(await res.text())
      setResult(await res.json())
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Generation failed')
    } finally { setLoading(false) }
  }, [form])

  const copyToClipboard = async () => {
    if (!result) return
    await navigator.clipboard.writeText(result.disclosure)
    setCopied(true); setTimeout(() => setCopied(false), 2000)
  }

  const downloadDoc = () => {
    if (!result) return
    const header = [
      `SFDR ARTICLE ${result.sfdr_article} PRE-CONTRACTUAL DISCLOSURE`,
      `Fund: ${result.fund_name}`,
      `Generated: ${new Date(result.generated_at).toLocaleString()}`,
      `Regulations: ${result.regulation_refs.join(' · ')}`,
      '', '='.repeat(70), '',
    ].join('\n')
    const footer = [
      '', '='.repeat(70),
      result.disclaimer,
      'This document was generated by Genesis Swarm RegTech Platform.',
    ].join('\n')
    const blob = new Blob([header + result.disclosure + footer], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a'); a.href = url
    a.download = `SFDR_Art${result.sfdr_article}_${result.fund_name.replace(/\s+/g,'_')}_${new Date().toISOString().slice(0,10)}.txt`
    a.click(); URL.revokeObjectURL(url)
  }

  const artInfo = ARTICLE_INFO[form.sfdr_article as keyof typeof ARTICLE_INFO]

  return (
    <div className="min-h-screen bg-[#050a0e] text-white font-mono">
      <div className="border-b border-[rgba(0,255,136,0.1)] px-6 py-3 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <a href="/operator" className="text-[10px] text-[rgba(255,255,255,0.4)] hover:text-white flex items-center gap-1"><ArrowLeft className="w-3 h-3" /> Dashboard</a>
          <div className="w-px h-4 bg-[rgba(255,255,255,0.1)]" />
          <div className="flex items-center gap-2">
            <FileText className="w-4 h-4 text-[#00aaff]" />
            <span className="text-sm font-bold tracking-widest text-[#00aaff]">SFDR DISCLOSURE GENERATOR</span>
          </div>
        </div>
        <div className="text-[9px] text-[rgba(255,255,255,0.3)] uppercase tracking-wider">EU 2019/2088 · RTS 2022/1288 · ESMA</div>
      </div>

      <div className="max-w-5xl mx-auto px-6 py-8">
        <div className={`grid gap-8 ${result ? 'grid-cols-1 lg:grid-cols-2' : 'grid-cols-1 max-w-2xl mx-auto'}`}>

          {/* Form panel */}
          <div className="space-y-5">
            <div>
              <h1 className="text-xl font-black mb-1">Generate SFDR Disclosure</h1>
              <p className="text-xs text-[rgba(255,255,255,0.4)]">AI-drafted pre-contractual disclosure per ESMA RTS 2022/1288 Annex II/III. Review with legal counsel before publishing.</p>
            </div>

            {/* Article selector */}
            <div className="space-y-2">
              <label className="block text-[10px] text-[rgba(255,255,255,0.4)] uppercase tracking-wider">SFDR Article Classification</label>
              <div className="grid grid-cols-3 gap-2">
                {(['6','8','9'] as const).map(art => {
                  const info = ARTICLE_INFO[art]
                  const active = form.sfdr_article === art
                  return (
                    <button key={art} onClick={() => set('sfdr_article', art)}
                      className={`p-3 rounded border text-left transition-all ${active ? 'border-current bg-[rgba(255,255,255,0.04)]' : 'border-[rgba(255,255,255,0.08)] hover:border-[rgba(255,255,255,0.15)]'}`}
                      style={active ? { color: info.color, borderColor: info.color + '66' } : {}}>
                      <div className="text-[11px] font-bold">{info.label}</div>
                    </button>
                  )
                })}
              </div>
              <div className="p-3 border border-[rgba(255,255,255,0.07)] bg-[rgba(255,255,255,0.02)] rounded text-[11px] text-[rgba(255,255,255,0.5)] flex gap-2">
                <Info className="w-3.5 h-3.5 flex-shrink-0 mt-0.5" style={{ color: artInfo.color }} />
                {artInfo.desc}
              </div>
            </div>

            <Field value={form.fund_name} onChange={v => set('fund_name', v)} label="Fund Name *" placeholder="e.g. Acme Sustainable Luxembourg AIF" />
            <Field value={form.manager_name} onChange={v => set('manager_name', v)} label="AIFM / Manager Name" placeholder="e.g. Acme Asset Management S.A." />

            <div className="grid grid-cols-2 gap-4">
              <Select value={form.fund_type} onChange={v => set('fund_type', v)} label="Fund Type" options={[
                {value:'AIF',label:'AIF'},{value:'UCITS',label:'UCITS'},{value:'RAIF',label:'RAIF'},
              ]} />
              <Select value={form.language} onChange={v => set('language', v)} label="Language" options={[
                {value:'en',label:'English'},{value:'fr',label:'French (Français)'},
              ]} />
            </div>

            <Field value={form.investment_strategy} onChange={v => set('investment_strategy', v)} label="Investment Strategy" placeholder="e.g. ESG-screened global equity, excluding fossil fuels..." multiline />

            {form.sfdr_article === '9' && (
              <Field value={form.sustainability_objective} onChange={v => set('sustainability_objective', v)} label="Sustainable Investment Objective (Art. 9)" placeholder="e.g. achieve net-zero carbon emissions aligned with EU Taxonomy..." multiline />
            )}

            {form.sfdr_article === '8' && (
              <Field value={form.esg_features} onChange={v => set('esg_features', v)} label="Environmental / Social Characteristics (Art. 8)" placeholder="e.g. low carbon footprint, board gender diversity ≥40%..." multiline />
            )}

            <div className="space-y-2">
              <label className="block text-[10px] text-[rgba(255,255,255,0.4)] uppercase tracking-wider">Principal Adverse Impacts (PAI)</label>
              <div className="flex gap-2">
                {[{v:true,l:'PAI Considered'},{v:false,l:'PAI Not Considered'}].map(opt => (
                  <button key={String(opt.v)} onClick={() => set('pai_considered', opt.v)}
                    className={`flex-1 py-2 rounded border text-xs transition-colors ${form.pai_considered === opt.v ? 'border-[rgba(0,255,136,0.5)] bg-[rgba(0,255,136,0.06)] text-[#00ff88]' : 'border-[rgba(255,255,255,0.1)] text-[rgba(255,255,255,0.4)]'}`}>
                    {opt.l}
                  </button>
                ))}
              </div>
              {form.pai_considered && (
                <Field value={form.pai_indicators} onChange={v => set('pai_indicators', v)} label="Key PAI Indicators (optional)" placeholder="e.g. GHG emissions, board gender diversity, UN GC violations" />
              )}
            </div>

            <Field value={form.benchmark_index} onChange={v => set('benchmark_index', v)} label="Reference Benchmark (optional)" placeholder="e.g. MSCI World ESG Leaders Index" />

            {error && (
              <div className="flex items-center gap-2 p-3 border border-[rgba(255,51,102,0.3)] bg-[rgba(255,51,102,0.05)] rounded text-sm text-[#ff3366]">
                <AlertTriangle className="w-4 h-4 flex-shrink-0" /> {error}
              </div>
            )}

            <button onClick={generate} disabled={loading || !form.fund_name.trim()}
              className="w-full flex items-center justify-center gap-2 py-3 bg-[rgba(0,170,255,0.1)] border border-[rgba(0,170,255,0.5)] text-[#00aaff] rounded font-bold hover:bg-[rgba(0,170,255,0.15)] disabled:opacity-40 transition-colors">
              {loading ? <><Loader2 className="w-4 h-4 animate-spin" /> Generating disclosure…</> : <><FileText className="w-4 h-4" /> Generate SFDR Disclosure</>}
            </button>

            <p className="text-[10px] text-[rgba(255,255,255,0.25)] flex items-center gap-1">
              <Globe className="w-3 h-3" /> Powered by Groq Llama-3.3-70b · ~€0.001 per generation · Legal review required
            </p>
          </div>

          {/* Result panel */}
          {result && (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <div className="text-xs font-bold text-[rgba(255,255,255,0.6)] uppercase tracking-wider">Generated Disclosure</div>
                  <div className="text-[10px] text-[rgba(255,255,255,0.3)] mt-0.5">SFDR Article {result.sfdr_article} · {result.language === 'fr' ? 'French' : 'English'}</div>
                </div>
                <div className="flex gap-2">
                  <button onClick={copyToClipboard}
                    className="flex items-center gap-1.5 px-3 py-1.5 border border-[rgba(255,255,255,0.15)] text-[rgba(255,255,255,0.5)] rounded text-xs hover:border-[rgba(255,255,255,0.3)] transition-colors">
                    {copied ? <CheckCheck className="w-3.5 h-3.5 text-[#00ff88]" /> : <Copy className="w-3.5 h-3.5" />}
                    {copied ? 'Copied' : 'Copy'}
                  </button>
                  <button onClick={downloadDoc}
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-[rgba(0,170,255,0.08)] border border-[rgba(0,170,255,0.4)] text-[#00aaff] rounded text-xs hover:bg-[rgba(0,170,255,0.12)] transition-colors">
                    <Download className="w-3.5 h-3.5" /> Download .txt
                  </button>
                </div>
              </div>

              <div className="border border-[rgba(255,255,255,0.08)] rounded-lg bg-[rgba(255,255,255,0.02)] p-4 max-h-[65vh] overflow-y-auto">
                <pre className="text-[11px] text-[rgba(255,255,255,0.75)] whitespace-pre-wrap leading-relaxed font-mono">{result.disclosure}</pre>
              </div>

              <div className="flex gap-2 flex-wrap text-[9px] text-[rgba(255,255,255,0.3)]">
                {result.regulation_refs.map(r => (
                  <span key={r} className="px-2 py-0.5 border border-[rgba(255,255,255,0.08)] rounded">{r}</span>
                ))}
              </div>

              <div className="flex items-start gap-2 p-3 border border-[rgba(255,170,0,0.2)] bg-[rgba(255,170,0,0.03)] rounded text-[10px] text-[rgba(255,170,0,0.7)]">
                <AlertTriangle className="w-3.5 h-3.5 flex-shrink-0 mt-0.5" />
                {result.disclaimer}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
