"""
Ingress Contracts — Pydantic v2 strict schemas for the Genesis Swarm API boundary.

Every payload that enters the system through a mutating HTTP endpoint is validated
against one of these contracts *before* it can touch any internal queue, consensus
engine, or database.  The key security invariants enforced here are:

- **No extra fields** — ``extra='forbid'`` on every model; unmapped keys are
  rejected, preventing field-smuggling or fat-payload injection attacks.
- **No implicit coercions** — ``strict=True`` on scalar fields; a string ``"0"``
  is not a valid integer, preventing type-confusion exploits.
- **Overflow prevention** — all numeric fields have explicit upper bounds; none
  can overflow Python's ``int`` (which is arbitrary precision but would DoS
  downstream int-to-SQL or int-to-protobuf serialisers).
- **Regex-constrained identifiers** — every ID field has a compile-time pattern
  that rejects injection characters (null bytes, SQL specials, shell meta-chars).
- **Float-free financials** — ``MonetaryAmount.amount`` rejects IEEE-754 ``float``
  at the validator level; clients must send amounts as strings or integers.
- **Bounded free-text** — ``details`` dicts are capped at 32 entries, each key ≤
  64 chars, each string value ≤ 512 chars, with no nested objects.

Public surface
--------------
    CaseSubmitRequest       — POST /api/cases
    MerkleAnchorRequest     — POST /api/merkle/anchor
    SafeHavenRequest        — POST /operator/safe-haven
    TransactionRequest      — POST /api/v1/transactions  (internal bot→gateway)
    PBFTEnvelopeRequest     — POST /api/consensus/envelope  (external node→mesh)
    ComplianceCheckRequest  — POST /api/v1/compliance/check
    EscrowRequest           — POST /api/v1/escrow
    TenantOnboardRequest    — POST /api/v1/tenants
    BatchTransactionRequest — POST /api/v1/transactions/batch
    ROUTE_SCHEMA_MAP        — maps (METHOD, path-prefix) → contract class
"""
from __future__ import annotations

import re
from decimal import Decimal, InvalidOperation
from typing import Annotated, Any, Final, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

__all__ = [
    "CaseSubmitRequest",
    "MerkleAnchorRequest",
    "SafeHavenRequest",
    "TransactionRequest",
    "PBFTEnvelopeRequest",
    "ComplianceCheckRequest",
    "EscrowRequest",
    "TenantOnboardRequest",
    "BatchTransactionRequest",
    "ROUTE_SCHEMA_MAP",
]

# ── Numeric overflow ceilings ─────────────────────────────────────────────────

_MAX_AMOUNT: Final[Decimal] = Decimal("999_999_999_999_999.9999")
_MIN_AMOUNT: Final[Decimal] = Decimal("0.0001")
_MAX_INT64: Final[int] = 2**63 - 1
_MAX_BATCH_SIZE: Final[int] = 50
_MAX_DETAILS_KEYS: Final[int] = 32
_MAX_DETAIL_KEY_LEN: Final[int] = 64
_MAX_DETAIL_STR_LEN: Final[int] = 512
_MAX_BODY_STR_LEN: Final[int] = 4096

# ── Pre-compiled identifier patterns ─────────────────────────────────────────

_RE_TENANT_ID: Final[re.Pattern[str]] = re.compile(
    r"^[a-zA-Z0-9][a-zA-Z0-9_-]{0,63}$"
)
_RE_TX_ID: Final[re.Pattern[str]] = re.compile(
    r"^tx-[a-zA-Z0-9]{8,32}$"
)
_RE_ESCROW_ID: Final[re.Pattern[str]] = re.compile(
    r"^escrow-[a-zA-Z0-9]{8,32}$"
)
_RE_NODE_ID: Final[re.Pattern[str]] = re.compile(
    r"^[a-zA-Z0-9][a-zA-Z0-9_-]{0,31}$"
)
_RE_ROUND_ID: Final[re.Pattern[str]] = re.compile(
    r"^[A-F0-9]{8}$"  # 8-char upper-hex as generated by pbft_consensus
)
_RE_SHA256: Final[re.Pattern[str]] = re.compile(r"^[0-9a-f]{64}$")
_RE_ED25519_SIG: Final[re.Pattern[str]] = re.compile(r"^[0-9a-f]{128}$")
_RE_ED25519_KEY: Final[re.Pattern[str]] = re.compile(r"^[0-9a-f]{64}$")
_RE_ISO4217: Final[re.Pattern[str]] = re.compile(r"^[A-Z]{3}$")
_RE_BOT_TYPE: Final[re.Pattern[str]] = re.compile(r"^[A-Z][A-Z0-9_]{1,31}$")
_RE_DETAIL_KEY: Final[re.Pattern[str]] = re.compile(r"^[a-zA-Z][a-zA-Z0-9_.]{0,63}$")
_RE_SEMVER: Final[re.Pattern[str]] = re.compile(
    r"^\d{1,4}\.\d{1,4}\.\d{1,4}(?:-[a-zA-Z0-9.]{1,16})?$"
)

# ── Annotated shorthand types ─────────────────────────────────────────────────
# These pin both the Python type and the Pydantic field constraints in one place
# so they can be reused across models without repeating constraints.

TenantIDStr = Annotated[
    str,
    Field(min_length=1, max_length=64, pattern=r"^[a-zA-Z0-9][a-zA-Z0-9_-]{0,63}$"),
]
TxIDStr = Annotated[
    str,
    Field(min_length=11, max_length=35, pattern=r"^tx-[a-zA-Z0-9]{8,32}$"),
]
NodeIDStr = Annotated[
    str,
    Field(min_length=1, max_length=32, pattern=r"^[a-zA-Z0-9][a-zA-Z0-9_-]{0,31}$"),
]
SHA256Str = Annotated[
    str,
    Field(min_length=64, max_length=64, pattern=r"^[0-9a-f]{64}$"),
]
Ed25519SigStr = Annotated[
    str,
    Field(min_length=128, max_length=128, pattern=r"^[0-9a-f]{128}$"),
]
Ed25519PubKeyStr = Annotated[
    str,
    Field(min_length=64, max_length=64, pattern=r"^[0-9a-f]{64}$"),
]
CurrencyStr = Annotated[
    str,
    Field(min_length=3, max_length=3, pattern=r"^[A-Z]{3}$"),
]
UInt63 = Annotated[int, Field(ge=0, le=_MAX_INT64)]
AnomalyScore = Annotated[float, Field(ge=0.0, le=100.0)]

# ── Base contract ─────────────────────────────────────────────────────────────


class _BaseContract(BaseModel):
    """
    Ancestor of every ingress schema.

    Config
    ------
    extra='forbid':
        Any field not declared in the model causes a ``ValidationError``.
        This is the primary defence against fat-payload / field-smuggling attacks.
    frozen=True:
        Model instances are immutable after construction; prevents accidental
        mutation in middleware or route handlers.
    str_strip_whitespace=True:
        Leading/trailing whitespace is stripped from all ``str`` fields before
        pattern validation.  Prevents homoglyph padding tricks.
    str_max_length=4096:
        Hard cap on any single ``str`` field to protect downstream buffers.
    validate_default=True:
        Default values are run through validators, catching misconfigured defaults
        early rather than silently storing invalid values.
    populate_by_name=False:
        Aliases cannot shadow field names; prevents confusing double-binding.
    """

    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
        str_strip_whitespace=True,
        str_max_length=_MAX_BODY_STR_LEN,
        validate_default=True,
        populate_by_name=False,
    )


# ── Bounded free-text detail map ──────────────────────────────────────────────

_DETAIL_VALUE_TYPES = str | int | float | bool


def _validate_details(v: Any) -> dict[str, _DETAIL_VALUE_TYPES]:
    """
    Validate a free-form ``details`` mapping against injection-prevention rules.

    Args:
        v: The raw value to validate; must be a plain ``dict``.

    Returns:
        The validated ``dict[str, str | int | float | bool]``.

    Raises:
        ValueError: If ``v`` is not a dict, has too many keys, contains invalid
            key names, nested structures, or string values that exceed the cap.
    """
    if not isinstance(v, dict):
        raise ValueError("details must be a flat JSON object")
    if len(v) > _MAX_DETAILS_KEYS:
        raise ValueError(
            f"details must have at most {_MAX_DETAILS_KEYS} keys; got {len(v)}"
        )
    sanitised: dict[str, _DETAIL_VALUE_TYPES] = {}
    for raw_key, val in v.items():
        if not isinstance(raw_key, str):
            raise ValueError(f"details key must be a string; got {type(raw_key).__name__!r}")
        if len(raw_key) > _MAX_DETAIL_KEY_LEN:
            raise ValueError(
                f"details key {raw_key!r} exceeds {_MAX_DETAIL_KEY_LEN} chars"
            )
        if not _RE_DETAIL_KEY.match(raw_key):
            raise ValueError(
                f"details key {raw_key!r} must match [a-zA-Z][a-zA-Z0-9_.{{0,63}}]"
            )
        if isinstance(val, (dict, list)):
            raise ValueError(
                f"details[{raw_key!r}] is a nested structure; only scalars are allowed"
            )
        if isinstance(val, bool):
            sanitised[raw_key] = val
        elif isinstance(val, str):
            if len(val) > _MAX_DETAIL_STR_LEN:
                raise ValueError(
                    f"details[{raw_key!r}] string exceeds {_MAX_DETAIL_STR_LEN} chars"
                )
            sanitised[raw_key] = val
        elif isinstance(val, int):
            if val > _MAX_INT64 or val < -(_MAX_INT64 + 1):
                raise ValueError(
                    f"details[{raw_key!r}] integer outside int64 range"
                )
            sanitised[raw_key] = val
        elif isinstance(val, float):
            import math
            if not math.isfinite(val):
                raise ValueError(
                    f"details[{raw_key!r}] float is NaN or Inf — not allowed"
                )
            sanitised[raw_key] = val
        else:
            raise ValueError(
                f"details[{raw_key!r}] has unsupported type {type(val).__name__!r}"
            )
    return sanitised


def _parse_decimal_amount(v: Any) -> Decimal:
    """
    Convert a JSON-native amount representation to ``Decimal``.

    Rejects IEEE-754 ``float`` inputs to prevent precision loss on financial
    quantities.  Accepts integer cent/satoshi representations and decimal
    strings.

    Args:
        v: Raw input from JSON — expected to be ``str``, ``int``, or ``Decimal``.

    Returns:
        A ``Decimal`` value.

    Raises:
        ValueError: If ``v`` is a ``float``, an invalid decimal string, ``bool``,
            or any other unsupported type.
    """
    if isinstance(v, bool):
        raise ValueError("bool is not a valid amount type")
    if isinstance(v, float):
        raise ValueError(
            "Float amounts are rejected due to IEEE 754 precision risk. "
            "Send amounts as a JSON string (e.g., \"amount\": \"1234.56\") "
            "or as an integer number of smallest currency units."
        )
    if isinstance(v, Decimal):
        return v
    if isinstance(v, int):
        return Decimal(v)
    if isinstance(v, str):
        try:
            return Decimal(v)
        except InvalidOperation as exc:
            raise ValueError(f"Invalid decimal string {v!r}: {exc}") from exc
    raise ValueError(f"Unsupported amount type {type(v).__name__!r}")


# ── Sub-model: MonetaryAmount ─────────────────────────────────────────────────


class MonetaryAmount(_BaseContract):
    """
    A validated monetary quantity with an ISO 4217 currency code.

    The ``amount`` field rejects IEEE-754 ``float`` inputs and enforces both a
    minimum positive value and a maximum that fits within a 64-bit financial
    representation.

    Args:
        amount: The monetary amount as a decimal string, integer, or ``Decimal``.
        currency: ISO 4217 three-letter currency code (e.g., ``"EUR"``).

    Raises:
        ValidationError: If ``amount`` is a float, negative, zero, or overflows;
            or if ``currency`` does not match ``^[A-Z]{3}$``.
    """

    amount: Annotated[Decimal, Field(ge=_MIN_AMOUNT, le=_MAX_AMOUNT)]
    currency: CurrencyStr

    @field_validator("amount", mode="before")
    @classmethod
    def _coerce_amount(cls, v: Any) -> Decimal:
        return _parse_decimal_amount(v)


# ── CaseSubmitRequest ─────────────────────────────────────────────────────────


class CaseSubmitRequest(_BaseContract):
    """
    Payload for ``POST /api/cases`` — create a new investigation case.

    Args:
        bot_type: The detecting bot's type identifier (e.g., ``"NAV_DETECTOR"``).
        score: Anomaly confidence score in [0.0, 100.0].
        summary: Human-readable summary of the detected anomaly (max 2048 chars).
        notes: Optional analyst notes attached at creation (max 2048 chars).

    Raises:
        ValidationError: If ``bot_type`` contains invalid characters, ``score``
            is outside [0.0, 100.0], or any string exceeds its length cap.
    """

    bot_type: Annotated[
        str,
        Field(min_length=2, max_length=32, pattern=r"^[A-Z][A-Z0-9_]{1,31}$"),
    ]
    score: AnomalyScore
    summary: Annotated[str, Field(min_length=1, max_length=2048)]
    notes: Annotated[str, Field(max_length=2048)] = ""


# ── MerkleAnchorRequest ───────────────────────────────────────────────────────


class MerkleAnchorRequest(_BaseContract):
    """
    Payload for ``POST /api/merkle/anchor`` — anchor a consensus round's Merkle
    root on-chain.

    Args:
        round_id: 8-character upper-hex PBFT round ID.
        merkle_root: SHA-256 hex digest of the Merkle root to anchor.
        chain_id: Optional target blockchain identifier (e.g., ``"ethereum:1"``).

    Raises:
        ValidationError: If ``round_id`` or ``merkle_root`` don't match their
            respective hex patterns.
    """

    round_id: Annotated[
        str,
        Field(min_length=8, max_length=8, pattern=r"^[A-F0-9]{8}$"),
    ]
    merkle_root: SHA256Str
    chain_id: Annotated[
        str,
        Field(
            min_length=1,
            max_length=64,
            pattern=r"^[a-zA-Z0-9][a-zA-Z0-9:_-]{0,63}$",
        ),
    ] = "ethereum:1"


# ── SafeHavenRequest ─────────────────────────────────────────────────────────


class SafeHavenRequest(_BaseContract):
    """
    Payload for ``POST /operator/safe-haven`` — activate safe-haven mode.

    Args:
        reason: Human-readable justification for activating safe-haven mode.
        duration_s: How long safe-haven mode should remain active, in seconds.
            Capped at 86400 (24 h) to prevent indefinite lockdown via a stale API call.
        operator_id: The ID of the operator issuing the command.

    Raises:
        ValidationError: If ``duration_s`` is non-positive or exceeds 86400,
            or ``reason`` is empty.
    """

    reason: Annotated[str, Field(min_length=1, max_length=512)]
    duration_s: Annotated[int, Field(ge=1, le=86_400)] = 3600
    operator_id: Annotated[
        str,
        Field(min_length=1, max_length=64, pattern=r"^[a-zA-Z0-9][a-zA-Z0-9_-]{0,63}$"),
    ] = "system"


# ── TransactionRequest ────────────────────────────────────────────────────────

_TX_TYPES = Literal[
    "NAV_ANOMALY",
    "SANCTION",
    "ESCROW_CREATE",
    "ESCROW_RELEASE",
    "WIRE_TRANSFER",
    "COMPLIANCE_CHECK",
    "POSITION_BREACH",
    "SETTLEMENT_FAIL",
]


class TransactionRequest(_BaseContract):
    """
    Payload for ``POST /api/v1/transactions`` — submit a transaction to the
    PBFT consensus pipeline.

    Args:
        tx_id: Unique transaction ID matching ``tx-<8-32 alphanum>``.
        tx_type: Discriminator determining which PBFT consensus ruleset applies.
        tenant_id: The originating tenant's identifier.
        initiator_bot: The bot type that generated this transaction.
        score: Bot's confidence score for this event in [0.0, 100.0].
        amount: Optional monetary amount; required for financial transaction types.
        currency: ISO 4217 code; required when ``amount`` is provided.
        timestamp_ns: UNIX nanosecond timestamp; validated to be a reasonable
            value (post-2020, pre-2030 to catch clock-skew exploits).
        details: Optional flat dict of auxiliary evidence metadata.

    Raises:
        ValidationError: On any constraint violation.
        ValueError: If ``amount`` is supplied without ``currency`` or vice-versa.
    """

    tx_id: TxIDStr
    tx_type: _TX_TYPES
    tenant_id: TenantIDStr
    initiator_bot: Annotated[
        str,
        Field(min_length=2, max_length=32, pattern=r"^[A-Z][A-Z0-9_]{1,31}$"),
    ]
    score: AnomalyScore
    amount: Annotated[Decimal | None, Field(default=None, ge=_MIN_AMOUNT, le=_MAX_AMOUNT)]
    currency: CurrencyStr | None = None
    timestamp_ns: Annotated[
        int,
        Field(
            ge=1_577_836_800_000_000_000,  # 2020-01-01T00:00:00Z in ns
            le=1_893_456_000_000_000_000,  # 2030-01-01T00:00:00Z in ns
        ),
    ]
    details: dict[str, _DETAIL_VALUE_TYPES] = Field(default_factory=dict)

    @field_validator("amount", mode="before")
    @classmethod
    def _coerce_amount(cls, v: Any) -> Decimal | None:
        if v is None:
            return None
        return _parse_decimal_amount(v)

    @field_validator("details", mode="before")
    @classmethod
    def _validate_details_field(cls, v: Any) -> dict[str, _DETAIL_VALUE_TYPES]:
        if v is None:
            return {}
        return _validate_details(v)

    @model_validator(mode="after")
    def _check_amount_currency_coherence(self) -> "TransactionRequest":
        """Amount and currency must both be present or both absent."""
        has_amount = self.amount is not None
        has_currency = self.currency is not None
        if has_amount != has_currency:
            raise ValueError(
                "amount and currency must both be provided or both omitted; "
                f"got amount={'<set>' if has_amount else 'null'}, "
                f"currency={'<set>' if has_currency else 'null'}"
            )
        return self


# ── PBFTEnvelopeRequest ───────────────────────────────────────────────────────

_PBFT_PHASES = Literal[
    "PRE_PREPARE",
    "PREPARE",
    "COMMIT",
    "VIEW_CHANGE",
    "NEW_VIEW",
    "CHECKPOINT",
]


class PBFTEnvelopeRequest(_BaseContract):
    """
    Payload for ``POST /api/consensus/envelope`` — submit a PBFT consensus
    envelope directly via the HTTP API (used by external replica nodes that
    cannot reach the gRPC mesh).

    All cryptographic fields are validated for correct length and hex encoding.
    The signature is *not* verified at the schema level — that is the job of
    ``PBFTNode.handle_envelope()``.

    Args:
        phase: PBFT message phase.
        view: Current view number (non-negative, fits int64).
        seq: Sequence number (non-negative, fits int64).
        digest: SHA-256 hex digest of the request payload.
        sender_id: Sending node's stable identifier.
        ed25519_pubkey: Hex-encoded 32-byte Ed25519 public key of the sender.
        signature: Hex-encoded 64-byte Ed25519 signature over the envelope fields.
        payload_b64: Base64-encoded inner payload bytes (max 64 KiB).
        timestamp_ns: Envelope creation time in UNIX nanoseconds.
        merkle_root: SHA-256 hex Merkle root at the time of envelope creation.

    Raises:
        ValidationError: On any hex pattern mismatch or out-of-range numeric value.
    """

    phase: _PBFT_PHASES
    view: UInt63
    seq: UInt63
    digest: SHA256Str
    sender_id: NodeIDStr
    ed25519_pubkey: Ed25519PubKeyStr
    signature: Ed25519SigStr
    payload_b64: Annotated[str, Field(min_length=0, max_length=87_381)]  # 64 KiB in base64
    timestamp_ns: Annotated[
        int,
        Field(
            ge=1_577_836_800_000_000_000,
            le=1_893_456_000_000_000_000,
        ),
    ]
    merkle_root: SHA256Str


# ── ComplianceCheckRequest ────────────────────────────────────────────────────

_COMPLIANCE_CHECKS = Literal[
    "OFAC_SDN",
    "EU_CONSOLIDATED",
    "UN_SANCTIONS",
    "FATF_GREY",
    "PEP_SCREENING",
    "AML_VELOCITY",
]


class ComplianceCheckRequest(_BaseContract):
    """
    Payload for ``POST /api/v1/compliance/check`` — request a sanctions or AML
    compliance screening.

    Args:
        check_type: The specific compliance rulebook to apply.
        subject_id: Opaque identifier for the subject being screened
            (entity ID, account number, or similar).
        subject_name: Displayable name of the subject (for fuzzy-matching).
        country_code: ISO 3166-1 alpha-2 country code of the subject.
        amount: Optional transaction amount involved in this check.
        currency: ISO 4217 code; required when ``amount`` is provided.
        tenant_id: Tenant requesting the check.
        reference_tx_id: Optional link to the originating transaction.

    Raises:
        ValidationError: On any constraint violation.
    """

    check_type: _COMPLIANCE_CHECKS
    subject_id: Annotated[
        str,
        Field(min_length=1, max_length=128, pattern=r"^[a-zA-Z0-9][a-zA-Z0-9._@:/-]{0,127}$"),
    ]
    subject_name: Annotated[str, Field(min_length=1, max_length=256)]
    country_code: Annotated[
        str,
        Field(min_length=2, max_length=2, pattern=r"^[A-Z]{2}$"),
    ]
    amount: Annotated[Decimal | None, Field(default=None, ge=_MIN_AMOUNT, le=_MAX_AMOUNT)]
    currency: CurrencyStr | None = None
    tenant_id: TenantIDStr
    reference_tx_id: TxIDStr | None = None

    @field_validator("amount", mode="before")
    @classmethod
    def _coerce_amount(cls, v: Any) -> Decimal | None:
        if v is None:
            return None
        return _parse_decimal_amount(v)

    @model_validator(mode="after")
    def _check_amount_currency_coherence(self) -> "ComplianceCheckRequest":
        has_amount = self.amount is not None
        has_currency = self.currency is not None
        if has_amount != has_currency:
            raise ValueError("amount and currency must both be provided or both omitted")
        return self


# ── EscrowRequest ─────────────────────────────────────────────────────────────

_ESCROW_CONDITIONS = Literal["TIME_LOCK", "MULTI_SIG", "ORACLE_TRIGGER", "PBFT_QUORUM"]


class EscrowRequest(_BaseContract):
    """
    Payload for ``POST /api/v1/escrow`` — create a new escrow contract.

    Args:
        escrow_id: Client-generated unique escrow identifier.
        payer_tenant_id: Tenant depositing funds into escrow.
        beneficiary_tenant_id: Tenant to receive funds upon condition satisfaction.
        amount: Escrowed monetary amount (decimal string or integer).
        currency: ISO 4217 currency code.
        condition_type: The release condition mechanism.
        release_at_ns: UNIX nanosecond timestamp; required for ``TIME_LOCK``
            conditions; ignored for others.
        required_signers: For ``MULTI_SIG`` — a list of signer node IDs (2–11).
        oracle_endpoint: For ``ORACLE_TRIGGER`` — an HTTPS URL to the price
            oracle (max 512 chars, must start with ``https://``).
        details: Optional auxiliary metadata.

    Raises:
        ValidationError: On constraint violation.
        ValueError: If ``TIME_LOCK`` is missing ``release_at_ns``, or
            ``MULTI_SIG`` has the wrong number of signers.
    """

    escrow_id: Annotated[
        str,
        Field(min_length=15, max_length=41, pattern=r"^escrow-[a-zA-Z0-9]{8,32}$"),
    ]
    payer_tenant_id: TenantIDStr
    beneficiary_tenant_id: TenantIDStr
    amount: Annotated[Decimal, Field(ge=_MIN_AMOUNT, le=_MAX_AMOUNT)]
    currency: CurrencyStr
    condition_type: _ESCROW_CONDITIONS
    release_at_ns: Annotated[int | None, Field(ge=0, le=_MAX_INT64)] = None
    required_signers: list[NodeIDStr] = Field(default_factory=list, max_length=11)
    oracle_endpoint: Annotated[
        str | None,
        Field(
            default=None,
            min_length=8,
            max_length=512,
            pattern=r"^https://[a-zA-Z0-9._/-]{1,490}$",
        ),
    ] = None
    details: dict[str, _DETAIL_VALUE_TYPES] = Field(default_factory=dict)

    @field_validator("amount", mode="before")
    @classmethod
    def _coerce_amount(cls, v: Any) -> Decimal:
        return _parse_decimal_amount(v)

    @field_validator("details", mode="before")
    @classmethod
    def _validate_details_field(cls, v: Any) -> dict[str, _DETAIL_VALUE_TYPES]:
        if v is None:
            return {}
        return _validate_details(v)

    @model_validator(mode="after")
    def _validate_condition_fields(self) -> "EscrowRequest":
        """Enforce condition-type-specific required fields."""
        if self.condition_type == "TIME_LOCK" and self.release_at_ns is None:
            raise ValueError("TIME_LOCK escrows require release_at_ns")
        if self.condition_type == "MULTI_SIG":
            if len(self.required_signers) < 2:
                raise ValueError(
                    "MULTI_SIG escrows require at least 2 required_signers"
                )
            if len(set(self.required_signers)) != len(self.required_signers):
                raise ValueError("required_signers must not contain duplicates")
        if self.condition_type == "ORACLE_TRIGGER" and self.oracle_endpoint is None:
            raise ValueError("ORACLE_TRIGGER escrows require oracle_endpoint")
        if self.payer_tenant_id == self.beneficiary_tenant_id:
            raise ValueError("payer and beneficiary must be different tenants")
        return self


# ── TenantOnboardRequest ──────────────────────────────────────────────────────

_BILLING_TIERS = Literal["FREE", "STARTER", "PROFESSIONAL", "ENTERPRISE"]


class TenantOnboardRequest(_BaseContract):
    """
    Payload for ``POST /api/v1/tenants`` — register a new tenant.

    Args:
        tenant_id: Desired tenant identifier (must not already exist).
        display_name: Human-readable name shown in the dashboard.
        billing_tier: Initial billing tier.
        contact_email: Administrative contact email for the tenant.
        jurisdiction: ISO 3166-1 alpha-2 country code of the tenant's legal
            jurisdiction (used for DORA and MiCA compliance routing).
        version: Client SDK version string (semver, used for deprecation notices).

    Raises:
        ValidationError: On any constraint violation.
    """

    tenant_id: TenantIDStr
    display_name: Annotated[str, Field(min_length=1, max_length=128)]
    billing_tier: _BILLING_TIERS = "FREE"
    contact_email: Annotated[
        str,
        Field(
            min_length=5,
            max_length=256,
            pattern=r"^[a-zA-Z0-9._%+\-]{1,64}@[a-zA-Z0-9.\-]{1,190}\.[a-zA-Z]{2,10}$",
        ),
    ]
    jurisdiction: Annotated[
        str,
        Field(min_length=2, max_length=2, pattern=r"^[A-Z]{2}$"),
    ] = "EU"
    version: Annotated[
        str,
        Field(
            min_length=5,
            max_length=32,
            pattern=r"^\d{1,4}\.\d{1,4}\.\d{1,4}(?:-[a-zA-Z0-9.]{1,16})?$",
        ),
    ] = "0.5.0"


# ── BatchTransactionRequest ───────────────────────────────────────────────────


class BatchTransactionRequest(_BaseContract):
    """
    Payload for ``POST /api/v1/transactions/batch`` — submit multiple
    transactions in a single atomic ingress call.

    Each element in ``transactions`` is independently validated as a
    ``TransactionRequest``.  If any element fails validation the entire batch
    is rejected with the per-element error detail.

    Args:
        transactions: List of 1–50 ``TransactionRequest`` objects.
        batch_id: Client-generated unique identifier for this batch.
        tenant_id: Tenant submitting the batch; must match every transaction's
            ``tenant_id`` field to prevent cross-tenant injection via batch.

    Raises:
        ValidationError: If the list is empty, exceeds 50 items, any element
            fails its own validation, or any transaction's tenant_id mismatches
            ``batch_id``'s ``tenant_id``.
    """

    transactions: Annotated[
        list[TransactionRequest],
        Field(min_length=1, max_length=_MAX_BATCH_SIZE),
    ]
    batch_id: Annotated[
        str,
        Field(min_length=8, max_length=64, pattern=r"^batch-[a-zA-Z0-9]{1,57}$"),
    ]
    tenant_id: TenantIDStr

    @model_validator(mode="after")
    def _check_tenant_consistency(self) -> "BatchTransactionRequest":
        """Every transaction in the batch must belong to the same tenant."""
        mismatches = [
            (i, tx.tenant_id)
            for i, tx in enumerate(self.transactions)
            if tx.tenant_id != self.tenant_id
        ]
        if mismatches:
            detail = ", ".join(f"[{i}]={tid!r}" for i, tid in mismatches[:5])
            raise ValueError(
                f"Batch tenant_id={self.tenant_id!r} but transactions have "
                f"different tenant IDs: {detail}"
            )
        return self


# ── Route → schema mapping ────────────────────────────────────────────────────

ValidationSchemaType = type[_BaseContract]

ROUTE_SCHEMA_MAP: dict[tuple[str, str], ValidationSchemaType] = {
    # (HTTP_METHOD, path_prefix): schema_class
    ("POST", "/api/cases"): CaseSubmitRequest,
    ("POST", "/api/merkle/anchor"): MerkleAnchorRequest,
    ("POST", "/operator/safe-haven"): SafeHavenRequest,
    ("POST", "/api/v1/transactions/batch"): BatchTransactionRequest,
    ("POST", "/api/v1/transactions"): TransactionRequest,
    ("POST", "/api/consensus/envelope"): PBFTEnvelopeRequest,
    ("POST", "/api/v1/compliance/check"): ComplianceCheckRequest,
    ("POST", "/api/v1/escrow"): EscrowRequest,
    ("POST", "/api/v1/tenants"): TenantOnboardRequest,
}
